config:
  #Write the base command for the plugin.
  base_command: "tag"
  #The placeholder would be %tag_player%
  placeholder: "tag"
  permissions:
    create_permission: "tag.create"
    colored_permission: "tag.color"
    admin_permission: "tag.admin"
  #Set the max-length of a tag name.
  max-length: 20
  #Set the price of the create command.
  cost: 100
  #Set the color code for default tags.
  default_color: "&7"
  #blacklist words
  blacklist:
    - "owner"

